### ISSUE TITLE
Make acisops/acispy be prime?

### ISSUE THREAD

**Issue by taldcroft** [acisops/acispy#1]
Currently `acisops/acispy` is a fork of `jzuhone/acispy`.  This (apparently) means you cannot open issues on `acisops/acispy`.  With the right permissions (which you have) one can transfer a repo.

**Comment by jzuhone** [comment]
@taldcroft how do you transfer the direction of the prime?

**Comment by jzuhone** [comment]
I guess we have to delete the fork and transfer.

**Comment by jzuhone** [comment]
I've done this now--acisops/acispy is prime.
