### ISSUE TITLE
Provide namespace prefix for scripts?

### ISSUE THREAD

**Issue by taldcroft** [acisops/acispy#2]
Would it be possible to make the scripts be prefixed by `acispy_` to give them a namespace?  Currently there are script names like `plot_model` going into the global Ska3 bin dir, which is not entirely ideal. Apart from potentially breaking current usage, this would probably be convenient because one could do `acispy_<TAB>` to discover those scripts.

**Comment by jzuhone** [comment]
I'm open to this.

**Comment by jzuhone** [comment]
@taldcroft I've decided to resolve this a separate way, by just removing the command line scripts and moving them to a separate package: PR #3

**Comment by jzuhone** [comment]
Resolved by #3.
